<a href="https://colab.research.google.com/github/shubhamgoel90/Pytorch-Basics/blob/master/pytorch_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from pathlib import Path
import torch
from torch.nn import functional as F
import torch.nn as nn
import math

In [0]:
x=torch.tensor([1,2,3])

In [0]:
import requests

DATA_PATH = Path("data")
PATH = DATA_PATH / "mnist"

PATH.mkdir(parents=True, exist_ok=True)

URL = "http://deeplearning.net/data/mnist/"
FILENAME = "mnist.pkl.gz"

if not (PATH / FILENAME).exists():
        content = requests.get(URL + FILENAME).content
        (PATH / FILENAME).open("wb").write(content)

In [0]:
import pickle
import gzip

with gzip.open((PATH / FILENAME).as_posix(), "rb") as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding="latin-1")

In [0]:
ds = pd.read_csv('sample_data/mnist_train_small.csv',header=None)
ds.head()

0    1    2    3    4    5    6    ...  778  779  780  781  782  783  784
0    6    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    5    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2    7    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    9    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    5    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 785 columns]

In [0]:
ds.shape

(20000, 785)

In [0]:
x_train.shape,y_train.shape,x_valid.shape,y_valid.shape

((50000, 784), (50000,), (10000, 784), (10000,))

In [0]:
y_train[:5]

array([5, 0, 4, 1, 9])

In [0]:
x_train= torch.tensor(x_train)
y_train = torch.

In [0]:
x_train, y_train, x_valid, y_valid = map(
    torch.tensor, (x_train, y_train, x_valid, y_valid)
)

In [0]:
x_train,y_train

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]), tensor([5, 0, 4,  ..., 8, 4, 8]))

In [0]:
weights = torch.randn((784,10),req) / math.sqrt(784)   #xaivier initialization 
weights.requires_grad_()
bias = torch.randn(10,requires_grad=True)

In [0]:
## log softmax understanding

In [0]:
t= torch.randn(2,4);t

tensor([[ 1.1394,  0.2265,  0.8822,  0.1170],
        [-0.3030, -0.6436, -0.3052,  0.3502]])

In [0]:
t.exp().sum(1).log().unsqueeze(1).shape

torch.Size([2, 1])

In [0]:
t.exp().sum(1).log().unsqueeze(1)

tensor([[1.8177],
        [2.0261]])

In [0]:
t  - t.exp().sum(1).log().unsqueeze(1)

tensor([[-0.9299, -1.8428, -1.1871, -1.9523],
        [-1.5327, -1.8733, -1.5349, -0.8796]])

In [0]:
0.4558 - 1.8177

-1.3619

In [0]:
def log_softmax(t):  
  return t - t.exp().sum(1).log().unsqueeze(1)

In [0]:
def model(xb):
  return log_softmax(xb@weights +  bias)

In [0]:
bs = 32 
xb = x_train[:32]
yb = y_train[:32]

preds = model(xb);preds.shape

torch.Size([32, 10])

In [0]:
xb.shape

torch.Size([32, 784])

In [0]:
def nll(xp,xt):
  return -xp[range(xt.shape[0]),xt].mean()

tensor(3.6498)

In [0]:
nll(preds,yb)

tensor(2.7658, grad_fn=<NegBackward>)

In [0]:
loss_fn = nll

In [0]:
lr = 0.01

In [0]:
# one batch pass

xb = x_train[:32]
yb = y_train[:32]

preds = model(xb)
loss = loss_fn(preds,yb)
print (loss)
loss.backward()

with torch.no_grad():
  weights -= weights.grad * lr
  bias -= bias.grad * lr
  weights.grad.zero_()
  bias.grad.zero_()

tensor(2.6355, grad_fn=<NegBackward>)


In [0]:
class model(nn.Module):
  def __init__(self,in_dim,out_dim):
    super().__init__()
    self.layer = nn.Linear(in_dim,out_dim)
  
  def forward(self,xb):
    return F.log_softmax(self.layer(xb))

In [0]:
class model2(nn.Module):
  def __init__(self):
    super().__init__()
    self.l1 = nn.Linear(784,256)
    self.l2 = nn.Linear(256,10)
  def forward(self,xb):
    out1 = F.relu(self.l1(xb))  # bs,784 --> bs,256
    return F.log_softmax(self.l2(out1))  ## bs,10

In [0]:
m=model2();m

model2(
  (l1): Linear(in_features=784, out_features=256, bias=True)
  (l2): Linear(in_features=256, out_features=10, bias=True)
)

In [0]:
m = model(784,10);m

model(
  (layer): Linear(in_features=784, out_features=10, bias=True)
)

In [0]:
# optimizers 

from torch import optim

opt = optim.Adam(m.parameters(),lr=1e-2)
opt = optim.SGD(m.parameters(),lr=0.01)


In [0]:
xb = x_train[:32]
yb = y_train[:32]

preds = m(xb)
loss = loss_fn(preds,yb)
print (loss)
loss.backward()

opt.step()
opt.zero_grad()

tensor(2.1694, grad_fn=<NegBackward>)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  import sys


In [0]:
#Steps
# 1. Create model 
# 2. Get preds 
# 3. Calculate loss
# 4. Calculate Grads
# 5. Optimize using SGD/Adam

In [0]:
x_train.shape,y_train.shape

(torch.Size([50000, 784]), torch.Size([50000]))

In [0]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
bs = 300
train_ds = TensorDataset(x_train[:1000], y_train[:1000])
train_dl = DataLoader(train_ds, batch_size=bs,ignore)

In [0]:
for xb,yb in train_dl:
  print (xb.shape,yb.shape)

torch.Size([300, 784]) torch.Size([300])
torch.Size([300, 784]) torch.Size([300])
torch.Size([300, 784]) torch.Size([300])
torch.Size([100, 784]) torch.Size([100])


In [0]:
train_ds[0][0].shape,train_ds[0][1]

(torch.Size([784]), tensor(5))

In [0]:
epochs = 5

In [0]:
for e in range(epochs):
  net_loss = 0
  for xb,yb in train_dl:
    preds = m(xb)
    loss = F.cross_entropy(preds,yb)
    loss.backward()
    net_loss += (loss)*xb.shape[0]
    opt.step()
    opt.zero_grad()
  print (net_loss/len(train_dl))

tensor(274.5184, grad_fn=<DivBackward0>)
tensor(264.1376, grad_fn=<DivBackward0>)
tensor(254.5071, grad_fn=<DivBackward0>)
tensor(245.5160, grad_fn=<DivBackward0>)
tensor(237.0934, grad_fn=<DivBackward0>)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  import sys


In [0]:
for p in m.parameters():
  print (p.shape,p.requires_grad)
  #p.requires_grad=False

torch.Size([10, 784]) False
torch.Size([10]) False
